Task: "JointTrainAgent"

BasicSettings:
  Seed: 0
  ImageSize: 64
  ReplayBufferOnGPU: True

JointTrainAgent:
  SampleMaxSteps: 102000
  BufferMaxLength: 100000
  BufferWarmUp: 1024
  NumEnvs: 1
  BatchSize: 32
  DemonstrationBatchSize: 4
  BatchLength: 32
  ImagineBatchSize: 512
  ImagineDemonstrationBatchSize: 256
  ImagineContextLength: 4
  ImagineBatchLength: 16
  TrainDynamicsEverySteps: 1
  TrainAgentEverySteps: 1
  UseDemonstration: False
  SaveEverySteps: 2500

Models:
  WorldModel:
    InChannels: 3
    TransformerMaxLength: 64
    TransformerHiddenDim: 256
    TransformerNumLayers: 2
    TransformerNumHeads: 4

  Agent:
    NumLayers: 2
    HiddenDim: 512
    Gamma: 0.985
    Lambda: 0.95
    EntropyCoef: 1e-3